<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Facades\Auth;

class Client extends Model
{
    use HasFactory;

    protected $fillable = [
        'district_id',
        'agent_id',
        'first_name',
        'last_name',
        'email',
        'phone',
        'dob',
        'passport_no',
        'nid_no',
        'address',
        'note',
        'description',
        'description',
        'status',
        'contract_price',
        'paid',
        'due',
        'created_by',
        'updated_by',
    ];

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Client $client) {
            $client->created_by = Auth::id() ?? 1;
            $client->updated_by = Auth::id() ?? 1;
        });

        static::updating(function (Client $client) {
            $client->updated_by = Auth::id();
        });
    }

    public function agent(): BelongsTo
    {
        return $this->belongsTo(Agent::class);
    }
    public function district(): BelongsTo
    {
        return $this->belongsTo(District::class);
    }
}
